"""Versioned contracts for compiled finite voxel worlds."""

from theseo_anysearch.worlds.artifacts import (
    GeometryArtifact,
    GeometryArtifactError,
    GeometryArtifactManifest,
    load_geometry_artifact,
    migrate_compiled_world,
    publish_eager_geometry,
)

from theseo_anysearch.worlds.candidates import (
    CandidateBudgetExceeded,
    CandidateIndexHandle,
    CandidateQueryBudget,
    CandidateRecord,
)
from theseo_anysearch.worlds.compiler import (
    BoxSource,
    CompiledWorld,
    NpySource,
    StlSource,
    WorldCompilerConfig,
    WorldPackCorruptError,
    WorldPackUnavailableError,
    benchmark_encodings,
    compile_pool,
    compile_world,
    decode_chunk,
    load_compiled_world,
    validate_compiled_world,
)
from theseo_anysearch.worlds.manifest import (
    COORDINATE_TYPE,
    ENVIRONMENT_COORDINATE_CONVENTION,
    STORAGE_COORDINATE_CONVENTION,
    WORLD_SCHEMA_VERSION,
    ChunkCoordinate,
    WorldChunkManifest,
    WorldExtent,
    WorldManifest,
    WorldOverviewManifest,
    world_contract,
    world_contract_fingerprint,
)
from theseo_anysearch.worlds.residency import (
    WorldResidencySettings,
    stage_compiled_world,
)
from theseo_anysearch.worlds.transformations import (
    SparseBox,
    SparseBoxTransform,
    SparseTransformedRead,
    generate_box_transform,
    measure_region_residency,
    transformed_artifact_metadata,
)

__all__ = [
    "COORDINATE_TYPE",
    "ENVIRONMENT_COORDINATE_CONVENTION",
    "GeometryArtifact",
    "GeometryArtifactError",
    "GeometryArtifactManifest",
    "STORAGE_COORDINATE_CONVENTION",
    "SparseBox",
    "SparseBoxTransform",
    "SparseTransformedRead",
    "WORLD_SCHEMA_VERSION",
    "BoxSource",
    "CandidateBudgetExceeded",
    "CandidateIndexHandle",
    "CandidateQueryBudget",
    "CandidateRecord",
    "ChunkCoordinate",
    "CompiledWorld",
    "NpySource",
    "StlSource",
    "WorldChunkManifest",
    "WorldCompilerConfig",
    "WorldExtent",
    "WorldManifest",
    "WorldOverviewManifest",
    "WorldPackCorruptError",
    "WorldPackUnavailableError",
    "WorldResidencySettings",
    "benchmark_encodings",
    "compile_pool",
    "compile_world",
    "decode_chunk",
    "load_compiled_world",
    "load_geometry_artifact",
    "migrate_compiled_world",
    "publish_eager_geometry",
    "stage_compiled_world",
    "validate_compiled_world",
    "world_contract",
    "world_contract_fingerprint",
    "generate_box_transform",
    "measure_region_residency",
    "transformed_artifact_metadata",
]
