import { useEffect, useRef, useState } from "react";
import {
  loadIterationHistory,
  scanTuneTrials,
  type TrajectoryData,
  type TrajectoryFile,
  type TrialInfo,
} from "../lib/tauri";

// Viewer module is generated by `npm run build:viewer` (wasm-pack build of
// ../viewer-web) into src/wasm/viewer/. It is not committed — build it once
// locally before `npm run dev`. See ../../README.md.
type ViewerModule = {
  default: (init?: unknown) => Promise<unknown>;
  start: (canvasId: string) => void;
  load_trajectories_json: (json: string) => void;
  set_position: (iterIdx: number, stepIdx: number) => void;
  set_occlude_agent: (occlude: boolean) => void;
};

const CANVAS_ID = "voxel-viewport";

function dirname(path: string): string {
  const idx = Math.max(path.lastIndexOf("/"), path.lastIndexOf("\\"));
  return idx >= 0 ? path.slice(0, idx) : path;
}

export default function ReplayPanel({
  file,
  onExplainStep,
}: {
  file: TrajectoryFile;
  onExplainStep?: (trajectorySourcePath: string, step: number) => void;
}) {
  const [trajectories, setTrajectories] = useState<TrajectoryData[]>([]);
  const [iterIdx, setIterIdx] = useState(0);
  const [stepIdx, setStepIdx] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [occludeAgent, setOccludeAgent] = useState(true);
  const [trials, setTrials] = useState<TrialInfo[]>([]);
  const [currentTrial, setCurrentTrial] = useState(0);
  const [viewerReady, setViewerReady] = useState(false);
  const [viewerError, setViewerError] = useState<string | null>(null);
  const viewerRef = useRef<ViewerModule | null>(null);

  // Load the full iteration history for this run/trial, then try to find a
  // sibling Tune-trial sweep (grandparent of trajectories/ holds trial dirs
  // with ray_runtime.json, per voxel_replay.rs's scan_tune_dir).
  useEffect(() => {
    let cancelled = false;
    const trajectoriesDir = dirname(file.path);
    loadIterationHistory(trajectoriesDir).then((data) => {
      if (cancelled) return;
      setTrajectories(data);
      setIterIdx(Math.max(0, data.length - 1));
      setStepIdx(0);
    });
    const tuneDir = dirname(dirname(trajectoriesDir));
    scanTuneTrials(tuneDir)
      .then((found) => {
        if (!cancelled) setTrials(found);
      })
      .catch(() => {
        if (!cancelled) setTrials([]);
      });
    return () => {
      cancelled = true;
    };
  }, [file.path]);

  function openTrial(index: number) {
    if (index < 0 || index >= trials.length) return;
    setCurrentTrial(index);
    loadIterationHistory(trials[index].trajectory_dir).then((data) => {
      setTrajectories(data);
      setIterIdx(Math.max(0, data.length - 1));
      setStepIdx(0);
    });
  }

  // Mount the wasm viewer once.
  useEffect(() => {
    let cancelled = false;
    // Loaded as `any`: the generated .d.ts only exists after `npm run
    // build:viewer` has been run locally (output is gitignored), so typing
    // this strictly would make a clean checkout fail `tsc -b`.
    import("../wasm/viewer/viewer_web.js")
      .then(async (mod: any) => {
        if (cancelled) return;
        await mod.default();
        const viewer = mod as ViewerModule;
        viewer.start(CANVAS_ID);
        viewerRef.current = viewer;
        setViewerReady(true);
      })
      .catch((e) => setViewerError(String(e?.message ?? e)));
    return () => {
      cancelled = true;
    };
  }, []);

  // Hand the full iteration set to the viewer whenever both it and the
  // viewer are ready (mount order between the two async loads isn't
  // guaranteed).
  useEffect(() => {
    if (viewerReady && trajectories.length > 0) {
      viewerRef.current?.load_trajectories_json(JSON.stringify(trajectories));
    }
  }, [viewerReady, trajectories]);

  useEffect(() => {
    viewerRef.current?.set_position(iterIdx, stepIdx);
  }, [iterIdx, stepIdx]);

  useEffect(() => {
    viewerRef.current?.set_occlude_agent(occludeAgent);
  }, [occludeAgent, viewerReady]);

  const traj = trajectories[iterIdx];
  const maxStep = (traj?.episode.steps.length ?? 1) - 1;
  const maxIter = trajectories.length - 1;

  // Playback: advance step, then iteration, matching voxel_replay.rs's
  // play_advance (stop at the last step of the last iteration).
  useEffect(() => {
    if (!playing) return;
    const id = setInterval(() => {
      setStepIdx((s) => {
        const currentMax = (trajectories[iterIdx]?.episode.steps.length ?? 1) - 1;
        if (s + 1 <= currentMax) return s + 1;
        setIterIdx((i) => {
          if (i + 1 <= trajectories.length - 1) return i + 1;
          setPlaying(false);
          return i;
        });
        return 0;
      });
    }, 120);
    return () => clearInterval(id);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [playing, trajectories]);

  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.target instanceof HTMLInputElement) return;
      if (e.key === "ArrowLeft") setStepIdx((s) => Math.max(0, s - 1));
      if (e.key === "ArrowRight") setStepIdx((s) => Math.min(maxStep, s + 1));
      if (e.key === "[") setIterIdx((i) => Math.max(0, i - 1));
      if (e.key === "]") setIterIdx((i) => Math.min(maxIter, i + 1));
      if (e.key === " ") {
        e.preventDefault();
        setPlaying((p) => !p);
      }
      if (e.key.toLowerCase() === "t") openTrial(Math.min(trials.length - 1, currentTrial + 1));
      if (e.key.toLowerCase() === "y") openTrial(Math.max(0, currentTrial - 1));
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [maxStep, maxIter, trials, currentTrial]);

  const step = traj?.episode.steps[stepIdx];
  const rewardCurve = traj?.episode.steps.map((s) => s.reward) ?? [];

  return (
    <div style={{ display: "flex", height: "100%" }}>
      <div style={{ flex: 1, position: "relative", background: "#0b0e14" }}>
        <canvas id={CANVAS_ID} style={{ width: "100%", height: "100%", display: "block" }} />
        {viewerError && (
          <div style={overlayStyle()}>
            Viewer not built yet — run `npm run build:viewer` in app-shell/web, then reload.
            <br />
            ({viewerError})
          </div>
        )}
      </div>

      <div style={{ width: 336, borderLeft: "1px solid #313131", background: "var(--panel)", overflowY: "auto" }}>
        <div style={{ padding: "18px 18px 14px", borderBottom: "1px solid var(--border-soft)" }}>
          <div style={{ fontSize: 19, fontWeight: 600 }}>Voxel Replay</div>
          <div style={{ marginTop: 8, fontSize: 11.5, color: "var(--text-dim)" }}>{file.name}</div>
        </div>

        {trials.length > 0 && (
          <div style={{ padding: 14, borderBottom: "1px solid var(--border-soft)" }}>
            <div style={groupLabel()}>Tune trial</div>
            <div style={{ fontSize: 12, color: "var(--text)" }}>
              Trial {currentTrial + 1} / {trials.length} · best reward {trials[currentTrial]?.best_reward.toFixed(3)}
            </div>
            <div style={{ display: "flex", gap: 6, marginTop: 8 }}>
              <NavButton label="|<" onClick={() => openTrial(0)} />
              <NavButton label="<" onClick={() => openTrial(currentTrial - 1)} />
              <NavButton label=">" onClick={() => openTrial(currentTrial + 1)} />
              <NavButton label=">|" onClick={() => openTrial(trials.length - 1)} />
            </div>
            <div style={hintStyle()}>trial T / Y keys</div>
          </div>
        )}

        <div style={{ padding: 14, borderBottom: "1px solid var(--border-soft)" }}>
          <div style={groupLabel()}>Iterations</div>
          <div style={{ fontSize: 12.5, fontFamily: "var(--mono)" }}>
            Iter {iterIdx + 1} <span style={{ color: "var(--text-dim)" }}>of {trajectories.length}</span> · mean reward{" "}
            {traj ? traj.episode.total_reward.toFixed(3) : "—"}
          </div>
          <input
            type="range"
            min={0}
            max={Math.max(maxIter, 0)}
            value={iterIdx}
            onChange={(e) => {
              setIterIdx(Number(e.target.value));
              setStepIdx(0);
            }}
            style={{ width: "100%", marginTop: 8, accentColor: "#565656" }}
          />
          <div style={{ display: "flex", gap: 6, marginTop: 6 }}>
            <NavButton label="|<" onClick={() => setIterIdx(0)} />
            <NavButton label="<" onClick={() => setIterIdx((i) => Math.max(0, i - 1))} />
            <NavButton label=">" onClick={() => setIterIdx((i) => Math.min(maxIter, i + 1))} />
            <NavButton label=">|" onClick={() => setIterIdx(maxIter)} />
          </div>
          <div style={hintStyle()}>[ / ] keys</div>
        </div>

        <div style={{ padding: 14, borderBottom: "1px solid var(--border-soft)" }}>
          <div style={groupLabel()}>Episode outcome</div>
          <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
            <Pill label="reward" value={traj?.episode.total_reward.toFixed(3) ?? "—"} />
            <Pill label="steps" value={`${traj?.episode.steps_taken ?? 0}`} />
            <Pill label="success" value={String(traj?.episode.success ?? false)} fail={traj ? !traj.episode.success : false} />
          </div>
        </div>

        <div style={{ padding: "14px 15px", borderLeft: "3px solid var(--blue)", background: "var(--panel-raised)" }}>
          <div style={{ ...groupLabel(), color: "#8fb8f5" }}>▸ Steps — active control</div>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
            <span style={{ fontSize: 14.5, fontWeight: 700, color: "#fff" }}>Step {stepIdx}</span>
            <span style={{ fontFamily: "var(--mono)", fontSize: 13, color: "var(--text-dim)" }}>/ {maxStep < 0 ? 0 : maxStep}</span>
          </div>
          <input
            type="range"
            min={0}
            max={Math.max(maxStep, 0)}
            value={stepIdx}
            onChange={(e) => setStepIdx(Number(e.target.value))}
            style={{ width: "100%", marginTop: 10, accentColor: "#3b93ff" }}
          />
          <div style={{ display: "flex", gap: 6, marginTop: 6 }}>
            <NavButton label="|<" onClick={() => setStepIdx(0)} />
            <NavButton label="<" onClick={() => setStepIdx((s) => Math.max(0, s - 1))} />
            <NavButton label=">" onClick={() => setStepIdx((s) => Math.min(maxStep, s + 1))} />
            <NavButton label=">|" onClick={() => setStepIdx(maxStep)} />
          </div>
          <div style={hintStyle()}>← / → keys</div>
        </div>

        <div style={{ padding: "14px 15px", borderLeft: "3px solid var(--blue)", background: "var(--panel-raised)", borderTop: "1px solid var(--border-soft)" }}>
          <div style={{ ...groupLabel(), color: "#8fb8f5" }}>▸ Current step</div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px 14px", marginTop: 12 }}>
            <Stat k="Action" v={String(step?.action ?? "—")} />
            <Stat k="Step reward" v={step ? step.reward.toFixed(3) : "—"} neg={step ? step.reward < 0 : false} />
            <Stat k="Cursor" v={step ? `${step.cursor_x}, ${step.cursor_y}, ${step.cursor_z}` : "—"} />
            <Stat k="Voxels" v={String(step?.voxel_count ?? "—")} />
          </div>
          {onExplainStep && traj && (
            <button
              onClick={() => onExplainStep(traj.source_path, stepIdx)}
              style={{ marginTop: 12, width: "100%", background: "var(--blue)", border: "none", borderRadius: 5, color: "#fff", padding: "6px 0", fontSize: 11.5, fontWeight: 600 }}
            >
              Explain current step
            </button>
          )}
        </div>

        <div style={{ padding: "14px 15px", borderLeft: "3px solid var(--blue)", background: "var(--panel-raised)", borderTop: "1px solid var(--border-soft)" }}>
          <div style={{ ...groupLabel(), color: "#8fb8f5" }}>▸ Playback</div>
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <button
              onClick={() => setPlaying((p) => !p)}
              style={{ display: "flex", alignItems: "center", gap: 6, background: "var(--blue)", color: "#fff", border: "none", padding: "6px 12px", borderRadius: 5, fontSize: 12.5, fontWeight: 600 }}
            >
              {playing ? "❚❚ Pause" : "▶ Play"}
            </button>
            <span style={{ fontSize: 11, color: "var(--text-faint)" }}>space plays every iteration</span>
          </div>
          <div style={{ marginTop: 12, display: "flex", alignItems: "center", justifyContent: "space-between" }}>
            <span style={{ fontSize: 12, color: "var(--text-dim)" }}>Geometry occludes agent &amp; trail</span>
            <div
              onClick={() => setOccludeAgent((v) => !v)}
              style={{
                width: 32,
                height: 18,
                borderRadius: 10,
                background: occludeAgent ? "var(--blue-soft, #1d3150)" : "#2a2a2a",
                border: `1px solid ${occludeAgent ? "var(--blue)" : "#3a3a3a"}`,
                position: "relative",
                cursor: "pointer",
              }}
            >
              <div
                style={{
                  position: "absolute",
                  top: 2,
                  left: occludeAgent ? 16 : 2,
                  width: 12,
                  height: 12,
                  borderRadius: "50%",
                  background: occludeAgent ? "var(--blue)" : "#6a6a6a",
                }}
              />
            </div>
          </div>
        </div>

        <div style={{ padding: 14 }}>
          <div style={groupLabel()}>Reward curve · this iteration</div>
          <RewardCurve values={rewardCurve} selected={stepIdx} />
        </div>
      </div>
    </div>
  );
}

function RewardCurve({ values, selected }: { values: number[]; selected: number }) {
  const width = 300;
  const height = 56;
  if (values.length < 2) {
    return (
      <div style={{ background: "#0c0e12", border: "1px solid var(--border-soft)", borderRadius: 4, padding: 14, fontSize: 11, color: "var(--text-faint)" }}>
        Not enough steps to chart.
      </div>
    );
  }
  const min = Math.min(0, ...values);
  const max = Math.max(0, ...values);
  const span = max - min || 1;
  const toY = (v: number) => height - ((v - min) / span) * height;
  const points = values.map((v, i) => `${(i / (values.length - 1)) * width},${toY(v)}`).join(" ");
  const zeroY = toY(0);
  const selX = (selected / (values.length - 1)) * width;

  return (
    <div style={{ background: "#0c0e12", border: "1px solid var(--border-soft)", borderRadius: 4, padding: "8px 10px 6px" }}>
      <svg viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" style={{ display: "block", width: "100%", height }}>
        <line x1={0} y1={zeroY} x2={width} y2={zeroY} stroke="#3d3d3d" strokeWidth={1} />
        <polyline points={points} fill="none" stroke="#3ecf83" strokeWidth={1.6} />
        <line x1={selX} y1={0} x2={selX} y2={height} stroke="#3b93ff" strokeWidth={1.4} strokeDasharray="2 2" />
        <circle cx={selX} cy={toY(values[selected] ?? 0)} r={2.4} fill="#3b93ff" />
      </svg>
      <div style={{ display: "flex", justifyContent: "space-between", marginTop: 6, fontSize: 9.5, color: "var(--text-faint)" }}>
        <span>step 0</span>
        <span>selected step marker</span>
        <span>step {values.length - 1}</span>
      </div>
    </div>
  );
}

function NavButton({ label, onClick }: { label: string; onClick: () => void }) {
  return (
    <button onClick={onClick} style={{ width: 26, height: 22, border: "none", background: "#2a2a2a", color: "#b7bdc6", borderRadius: 4, fontSize: 11, cursor: "pointer" }}>
      {label}
    </button>
  );
}

function overlayStyle(): React.CSSProperties {
  return {
    position: "absolute",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--text-faint)",
    fontFamily: "var(--mono)",
    fontSize: 12,
    padding: 24,
    textAlign: "center",
  };
}

function groupLabel(): React.CSSProperties {
  return { fontSize: 10, fontWeight: 700, letterSpacing: "0.07em", color: "var(--text-faint)", textTransform: "uppercase", marginBottom: 10 };
}

function hintStyle(): React.CSSProperties {
  return { marginTop: 8, fontSize: 10.5, color: "var(--text-faint)", fontFamily: "var(--mono)" };
}

function Pill({ label, value, fail }: { label: string; value: string; fail?: boolean }) {
  return (
    <span
      style={{
        fontSize: 11.5,
        fontFamily: "var(--mono)",
        padding: "4px 8px",
        borderRadius: 4,
        background: fail ? "#241315" : "#121212",
        border: `1px solid ${fail ? "#4a2226" : "var(--border-soft)"}`,
        color: fail ? "#ffb2b4" : "var(--text-dim)",
      }}
    >
      {label} <b style={{ color: fail ? "#ff8a8f" : "var(--text)" }}>{value}</b>
    </span>
  );
}

function Stat({ k, v, neg }: { k: string; v: string; neg?: boolean }) {
  return (
    <div>
      <div style={{ fontSize: 9.5, letterSpacing: "0.04em", textTransform: "uppercase", color: "var(--text-faint)", marginBottom: 2 }}>{k}</div>
      <div style={{ fontFamily: "var(--mono)", fontSize: 13, color: neg ? "var(--red)" : "var(--text)", fontWeight: neg ? 600 : 400 }}>
        {neg ? "▼ " : ""}
        {v}
      </div>
    </div>
  );
}
