import { useEffect, useRef, useState } from "react";
import { loadTrajectory, type TrajectoryData, type TrajectoryFile } from "../lib/tauri";

// Viewer module is generated by `npm run build:viewer` (wasm-pack build of
// ../viewer-web) into src/wasm/viewer/. It is not committed — build it once
// locally before `npm run dev`. See ../../README.md.
type ViewerModule = {
  default: (init?: unknown) => Promise<unknown>;
  start: (canvasId: string) => void;
  load_trajectories_json: (json: string) => void;
  set_position: (iterIdx: number, stepIdx: number) => void;
};

const CANVAS_ID = "voxel-viewport";

export default function ReplayPanel({ file }: { file: TrajectoryFile }) {
  const [traj, setTraj] = useState<TrajectoryData | null>(null);
  const [stepIdx, setStepIdx] = useState(0);
  const [viewerError, setViewerError] = useState<string | null>(null);
  const viewerRef = useRef<ViewerModule | null>(null);

  // Load the trajectory from disk via Tauri, then hand it to the wasm viewer.
  useEffect(() => {
    let cancelled = false;
    loadTrajectory(file.path).then((data) => {
      if (cancelled) return;
      setTraj(data);
      setStepIdx(0);
      viewerRef.current?.load_trajectories_json(JSON.stringify([data]));
    });
    return () => {
      cancelled = true;
    };
  }, [file.path]);

  // Mount the wasm viewer once.
  useEffect(() => {
    let cancelled = false;
    // Loaded as `any`: the generated .d.ts only exists after `npm run
    // build:viewer` has been run locally (output is gitignored), so typing
    // this strictly would make a clean checkout fail `tsc -b`.
    import("../wasm/viewer/viewer_web.js")
      .then(async (mod: any) => {
        if (cancelled) return;
        await mod.default();
        const viewer = mod as ViewerModule;
        viewer.start(CANVAS_ID);
        viewerRef.current = viewer;
        if (traj) viewer.load_trajectories_json(JSON.stringify([traj]));
      })
      .catch((e) => setViewerError(String(e?.message ?? e)));
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    viewerRef.current?.set_position(0, stepIdx);
  }, [stepIdx]);

  const step = traj?.episode.steps[stepIdx];
  const maxStep = (traj?.episode.steps.length ?? 1) - 1;

  return (
    <div style={{ display: "flex", height: "100%" }}>
      <div style={{ flex: 1, position: "relative", background: "#0b0e14" }}>
        <canvas id={CANVAS_ID} style={{ width: "100%", height: "100%", display: "block" }} />
        {viewerError && (
          <div
            style={{
              position: "absolute",
              inset: 0,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              color: "var(--text-faint)",
              fontFamily: "var(--mono)",
              fontSize: 12,
              padding: 24,
              textAlign: "center",
            }}
          >
            Viewer not built yet — run `npm run build:viewer` in app-shell/web, then reload.
            <br />
            ({viewerError})
          </div>
        )}
      </div>

      <div style={{ width: 336, borderLeft: "1px solid #313131", background: "var(--panel)", overflowY: "auto" }}>
        <div style={{ padding: "18px 18px 14px", borderBottom: "1px solid var(--border-soft)" }}>
          <div style={{ fontSize: 19, fontWeight: 600 }}>Voxel Replay</div>
          <div style={{ marginTop: 8, fontSize: 11.5, color: "var(--text-dim)" }}>{file.name}</div>
        </div>

        <div style={{ padding: 14, borderBottom: "1px solid var(--border-soft)" }}>
          <div style={groupLabel()}>Episode outcome</div>
          <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
            <Pill label="reward" value={traj?.episode.total_reward.toFixed(3) ?? "—"} />
            <Pill label="steps" value={`${traj?.episode.steps_taken ?? 0}`} />
            <Pill label="success" value={String(traj?.episode.success ?? false)} fail={traj ? !traj.episode.success : false} />
          </div>
        </div>

        <div style={{ padding: "14px 15px", borderLeft: "3px solid var(--blue)", background: "var(--panel-raised)" }}>
          <div style={{ ...groupLabel(), color: "#8fb8f5" }}>▸ Steps — active control</div>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
            <span style={{ fontSize: 14.5, fontWeight: 700, color: "#fff" }}>Step {stepIdx}</span>
            <span style={{ fontFamily: "var(--mono)", fontSize: 13, color: "var(--text-dim)" }}>/ {maxStep < 0 ? 0 : maxStep}</span>
          </div>
          <input
            type="range"
            min={0}
            max={Math.max(maxStep, 0)}
            value={stepIdx}
            onChange={(e) => setStepIdx(Number(e.target.value))}
            style={{ width: "100%", marginTop: 10, accentColor: "#3b93ff" }}
          />
        </div>

        <div style={{ padding: "14px 15px", borderLeft: "3px solid var(--blue)", background: "var(--panel-raised)", borderTop: "1px solid var(--border-soft)" }}>
          <div style={{ ...groupLabel(), color: "#8fb8f5" }}>▸ Current step</div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px 14px", marginTop: 12 }}>
            <Stat k="Action" v={String(step?.action ?? "—")} />
            <Stat k="Step reward" v={step ? step.reward.toFixed(3) : "—"} neg={step ? step.reward < 0 : false} />
            <Stat k="Cursor" v={step ? `${step.cursor_x}, ${step.cursor_y}, ${step.cursor_z}` : "—"} />
            <Stat k="Voxels" v={String(step?.voxel_count ?? "—")} />
          </div>
        </div>
      </div>
    </div>
  );
}

function groupLabel(): React.CSSProperties {
  return { fontSize: 10, fontWeight: 700, letterSpacing: "0.07em", color: "var(--text-faint)", textTransform: "uppercase", marginBottom: 10 };
}

function Pill({ label, value, fail }: { label: string; value: string; fail?: boolean }) {
  return (
    <span
      style={{
        fontSize: 11.5,
        fontFamily: "var(--mono)",
        padding: "4px 8px",
        borderRadius: 4,
        background: fail ? "#241315" : "#121212",
        border: `1px solid ${fail ? "#4a2226" : "var(--border-soft)"}`,
        color: fail ? "#ffb2b4" : "var(--text-dim)",
      }}
    >
      {label} <b style={{ color: fail ? "#ff8a8f" : "var(--text)" }}>{value}</b>
    </span>
  );
}

function Stat({ k, v, neg }: { k: string; v: string; neg?: boolean }) {
  return (
    <div>
      <div style={{ fontSize: 9.5, letterSpacing: "0.04em", textTransform: "uppercase", color: "var(--text-faint)", marginBottom: 2 }}>{k}</div>
      <div style={{ fontFamily: "var(--mono)", fontSize: 13, color: neg ? "var(--red)" : "var(--text)", fontWeight: neg ? 600 : 400 }}>
        {neg ? "▼ " : ""}
        {v}
      </div>
    </div>
  );
}
